[SD-206] Fixing the DiagnosedPublisher
mantis-tec/diagnostics pull request #1
Opened 2022-09-01 12:53 UTC by LoicFerrot

This corrects all the issues encountered so far with ros-foxy and the `DiagnosedPublisher` as well as various weird problems.

2022-09-01 18:15 UTC, KevinSchwarzer requested changes
Few things to consider regarding forks.

2022-09-01 18:15 UTC, KevinSchwarzer commented on diagnostic_updater/diagnostic_updater/_diagnostic_updater.py
> +                if self.verbose and status.level != b'\x00':
Just for my understanding. Would the comparison to `0x00` also work? Or does it need to be a byte string?

2022-09-01 18:15 UTC, KevinSchwarzer commented on diagnostic_updater/diagnostic_updater/_publisher.py
> +        self.stamp.tick(stamp_s)
IMO, we shouldn't change things that are not necessary to change in order to get this package to work. If we need to pull upstream changes, I'd rather have a few merge conflicts as possible. Hence, changing as few lines as possible leads to less merge conflicts.

- [ ] Revert unnecessary changes.

2022-09-01 18:15 UTC, KevinSchwarzer commented on diagnostic_updater/diagnostic_updater/_update_functions.py
> +                )
Same here. As long as the previous code worked, why bother changing it?

2022-09-01 18:15 UTC, KevinSchwarzer commented on diagnostic_updater/diagnostic_updater/_update_functions.py
> +                     f"{self.zero_count}")
Same argument as before. Why changing working code? Or isn't it working?

2022-09-02 13:25 UTC, LoicFerrot commented on diagnostic_updater/diagnostic_updater/_diagnostic_updater.py
> +                if self.verbose and status.level != b'\x00':
`b'\x00' == 0x00` --> `False`
It needs to be this byte string

2022-09-02 13:30 UTC, LoicFerrot commented on diagnostic_updater/diagnostic_updater/_publisher.py
> +        self.stamp.tick(stamp_s)
I find this parameter particularly critical, the two added characters are the result of a rather long debug process and will spare us a lot of confusion.
I agree with you about the strings refactoring though, it hurt my eyes but this is no excuse :smile:

2022-09-02 13:31 UTC, LoicFerrot commented on diagnostic_updater/diagnostic_updater/_update_functions.py
> +                     f"{self.zero_count}")
The summary modification is useful to avoid us some confusion IMO, I agree with you for the f-strings though.

2022-09-02 13:41 UTC, LoicFerrot commented on diagnostic_updater/diagnostic_updater/_update_functions.py
> +                )
In the idea I agree with you about unnecessary changes, but in practice the %-formatting was the source of a crash. Therefore, I would feel more comfortable knowing that changing an int to a float or the other way around will not be the source of a future crash.
Please tell me if you think it is nevertheless worth it to revert these changes

2022-09-12 08:22 UTC, kevinanschau commented on diagnostic_updater/diagnostic_updater/_update_functions.py
> +                )
I'm okay with the changes. Just keep in mind that the more lines you change, the more merge conflicts you'll get when pulling upstream changes, which will consume more of your time.

2022-09-12 08:22 UTC, kevinanschau approved these changes

2022-09-12 08:32 UTC, sttobia approved these changes

2022-09-12 09:12 UTC, LoicFerrot commented
Thanks!

2022-09-12 09:12 UTC, merged